= GPG Configuration Guide 🔑

== 1. Install GnuPG 

Refer to the documentation to download the appropriate GnuPG for your system. https://gnupg.org/download/index.html[Download link]

== 2. Generate a GPG key pair
 Open the software you just installed, create a key pair, and upload the public key.

== 3. Get the key information

Open your terminal and execute the following command:

[source,shell]
----
gpg -K
----

You will see the following output:

[source,text]
----------------------------------------
sec   rsa4096 2023-11-07 [SC] [valid till：2027-11-07]
      ⚠️[your-sec-key] 
uid           your-name <your-email>
ssb   rsa4096 2023-11-07 [E] [valid till：2027-11-07]
----------------------------------------

== 4. Export the secret

Next, execute the following command:

[source,shell]
----
gpg --keyring secring.gpg --export-secret-keys > ~/.gnupg/secring.gpg
----

Now, you need three pieces of information:

* `signing.keyId` - This is the `last eight bits` of `your-sec-key` that you see when you execute `gpg -K` in step 3.
* `signing.password` - This is the password you entered to protect your private key when you generated it in step 2.
* `signing.secretKeyRingFile` - This is the absolute path that you obtain when you execute `gpg --keyring secring.gpg --export-secret-keys > ~/.gnupg/secring.gpg` in step 4.


== 5. Set the configuration

Finally, store the above information in the Gradle configuration file (usually located at `~/.gradle/gradle.properties`), or provide them as environment variables:

[source,properties]
----
signing.keyId=24875D73
signing.password=secret
signing.secretKeyRingFile=/Users/me/.gnupg/secring.gpg
----

*💯 You have completed all the gpg configurations.*
